### ISSUE TITLE
Documentation has wrong links

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/solarchem-ontology#8]
https://w3id.org/solar/ has  http://w3id.org/solar/o/core, which is correct.

But http://w3id.org/solar/o/core redirects to https://oeg-upm.github.io/solarchem-ontology/release/1.0.0/core/index-en.html, which states that the core url is https://w3id.org/solarchem/sc/0.7.0. This is wrong. I think the wrong file was used to generate the doc.

**Comment by anaigmo** [comment]
This is fixed now with the new release
